from django.urls import path
from . import views

urlpatterns = [
    path(
        route="api/v1/accounts",
        view=views.UsersAPIView.as_view(),
        name="api-v1-accounts",
    ),
    path(
        route="api/v1/accounts/account-details/<int:pk>",
        view=views.UserDetailsAPIView.as_view(),
        name="api-v1-accounts-account-details",
    ),
    path(
        route="api/v1/profiles",
        view=views.ProfileAPIView.as_view(),
        name="api-v1-profiles",
    ),
    path(
        route="api/v1/profiles/profile-details/<int:pk>",
        view=views.ProfileDetailsAPIView.as_view(),
        name="api-v1-profiles-profile-details",
    ),
    path(
        route="api/v1/delivery-details/delivery-details-details/<int:pk>",
        view=views.DeliveryDetailsDetailsAPIView.as_view(),
        name="api-v1-delivery-details-delivery-details-details",
    ),
    path(
        route="api/v1/delivery-details",
        view=views.DeliveryDetailsAPIView.as_view(),
        name="api-v1-delivery-details",
    ),
    path(
        route="api/v1/accounts/account-register",
        view=views.UserRegisterAPIView.as_view(),
        name="api-v1-accounts-account-register",
    ),
    path(
        route="api/v1/accounts/account-login",
        view=views.UserLoginAPIView.as_view(),
        name="api-v1-accounts-account-login",
    ),
    path(
        route="activate/<uidb64>/<token>",
        view=views.activate,
        name="activate",
    ),
    path(
        route="log-out",
        view=views.UserLogoutAPIView.as_view(),
        name="logout",
    ),
    path(
        route="api/v1/accounts/forgot-password",
        view=views.ForgotPasswordAPIView.as_view(),
        name="api-v1-accounts-forgot-password",
    ),
    path(
        route="reset-password/<uidb64>/<str:email>/<uuid>",
        view=views.reset_password,
        name="reset-password",
    ),
    path(
        route="api/v1/accounts/change-password",
        view=views.ChangePasswordAPIView.as_view(),
        name="api-v1-accounts-change-password",
    ),
    path(
        route="api/v1/accounts/update-account",
        view=views.UserUpdateAPIView.as_view(),
        name="api-v1-accounts-update-account",
    ),
    path(
        route="api/v1/profiles/update-profile",
        view=views.ProfileUpdateAPIView.as_view(),
        name="api-v1-profiles-update-profile"
    ),
    path(
        route="api/v1/profiles/delete-profile-picture",
        view=views.ProfilePictureDeleteAPIView.as_view(),
        name="api-v1-profiles-delete-profile-picture",
    ),
    path(
        route="api/v1/delivery-details/update-delivery-details",
        view=views.DeliveryDetailsUpdateAPIView.as_view(),
        name="api-v1-delivery-details-update-delivery-details",
    ),
]
