# Generated by Django 5.0.6 on 2024-08-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmail",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contactmail",
            name="fullname",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="contactmail",
            name="message",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="contactmail",
            name="subject",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
