# Generated by Django 5.0.6 on 2024-07-22 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_sent", models.DateTimeField(default=django.utils.timezone.now)),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=150)),
                ("subject", models.CharField(max_length=150)),
                ("content", models.CharField(max_length=2000)),
            ],
            options={
                "verbose_name": "Contact Mail",
                "verbose_name_plural": "Contact Mails",
            },
        ),
    ]
