# Generated by Django 5.0.6 on 2024-07-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contactmail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmail",
            name="content",
            field=models.TextField(max_length=2000),
        ),
    ]
