# Generated by Django 5.0.6 on 2024-07-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_contactmail_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmail", old_name="content", new_name="message",
        ),
    ]
