# Generated by Django 5.0.6 on 2024-07-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_content_contactmail_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmail", old_name="full_name", new_name="fullname",
        ),
    ]
