# Generated by Django 5.0.6 on 2024-07-29 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="uuid", field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
