# Generated by Django 5.1 on 2024-09-01 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profilepicture_alt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="delivery_details",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.deliverydetails",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profilepicture",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.profilepicture",
            ),
        ),
    ]
