# Generated by Django 5.0.6 on 2024-08-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_images/default_profile_image.png",
                null=True,
                upload_to="profile_images",
            ),
        ),
    ]
