# Generated by Django 5.0.6 on 2024-08-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AddField(
            model_name="profile", name="website", field=models.URLField(null=True),
        ),
    ]
