# Generated by Django 5.0.6 on 2024-08-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_profile_picture_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="short_description", new_name="bio",
        ),
        migrations.RenameField(
            model_name="profile", old_name="website", new_name="facebook",
        ),
        migrations.RemoveField(model_name="profile", name="address_line",),
        migrations.AddField(
            model_name="profile",
            name="address_line_1",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="address_line_2",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile", name="instagram", field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.IntegerField(null=True),
        ),
    ]
