# Generated by Django 5.0.6 on 2024-08-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_short_description_profile_bio_and_more"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.IntegerField(null=True)),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=200)),
                ("house_number", models.CharField(max_length=200)),
                ("apartment_number", models.IntegerField()),
                ("postal_code", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(model_name="profile", name="address_line_1",),
        migrations.RemoveField(model_name="profile", name="address_line_2",),
        migrations.RemoveField(model_name="profile", name="city",),
        migrations.RemoveField(model_name="profile", name="country",),
        migrations.RemoveField(model_name="profile", name="phone_number",),
        migrations.RemoveField(model_name="profile", name="postal_code",),
        migrations.RemoveField(model_name="profile", name="state",),
        migrations.AddField(
            model_name="profile",
            name="wishlist",
            field=models.ManyToManyField(to="shop.product"),
        ),
    ]
