# Generated by Django 5.0.6 on 2024-08-10 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_deliverydetails_remove_profile_address_line_1_and_more"),
        ("shop", "0002_deliverydetails"),
    ]

    operations = [
        migrations.DeleteModel(name="DeliveryDetails",),
        migrations.AddField(
            model_name="profile",
            name="delivery_details",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.deliverydetails",
            ),
        ),
    ]
