# Generated by Django 5.0.6 on 2024-08-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_delete_deliverydetails_profile_delivery_details"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="image", new_name="profile_picture",
        ),
        migrations.RemoveField(model_name="profile", name="facebook",),
        migrations.RemoveField(model_name="profile", name="instagram",),
        migrations.AddField(
            model_name="profile",
            name="facebook_username",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_username",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
