# Generated by Django 5.0.6 on 2024-08-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_rename_image_profile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Not Set", "Not Set")]
            ),
        ),
    ]
