# Generated by Django 5.0.6 on 2024-08-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_profile_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="date_of_birth", new_name="dateofbirth",
        ),
        migrations.RenameField(
            model_name="profile", old_name="facebook_username", new_name="facebook",
        ),
        migrations.RenameField(
            model_name="profile", old_name="instagram_username", new_name="instagram",
        ),
        migrations.RenameField(
            model_name="profile", old_name="profile_picture", new_name="profilepicture",
        ),
    ]
