# Generated by Django 5.0.6 on 2024-08-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_profile_bio_alter_profile_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Undefined", "Undefined"),
                ],
                default="Undefined",
            ),
        ),
    ]
