# Generated by Django 5.0.6 on 2024-08-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="bio", field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="profile",
            name="facebook",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
