# Generated by Django 5.0.6 on 2024-08-14 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_onetimepassword"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("phone", models.CharField(max_length=20, null=True)),
                ("country", models.CharField(max_length=56)),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=169)),
                ("street", models.CharField(max_length=50)),
                ("housenumber", models.CharField(max_length=5)),
                ("apartmentnumber", models.CharField(max_length=5)),
                ("postalcode", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Delivery Detail",
                "verbose_name_plural": "Delivery Details",
            },
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="delivery_details",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.deliverydetails",
            ),
        ),
    ]
