# Generated by Django 5.0.6 on 2024-08-14 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_deliverydetails_alter_onetimepassword_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="delivery_details",),
        migrations.AddField(
            model_name="deliverydetails",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profile",
            ),
        ),
    ]
