# Generated by Django 5.0.6 on 2024-08-14 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_remove_profile_delivery_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="deliverydetails", name="profile",),
        migrations.AddField(
            model_name="profile",
            name="delivery_details",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.deliverydetails",
            ),
        ),
    ]
