# Generated by Django 5.0.6 on 2024-08-25 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_deliverydetails_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverydetails",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profilepicture",
            field=models.ImageField(
                default="profile_images/default_profile_image.png",
                null=True,
                upload_to="profile_images/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
