# Generated by Django 5.0.6 on 2024-08-26 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_deliverydetails_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="delivery_details",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.deliverydetails",
            ),
        ),
    ]
