# Generated by Django 5.0.6 on 2024-08-29 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_alter_profile_delivery_details"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="profilepicture",),
    ]
