# Generated by Django 5.0.6 on 2024-08-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_remove_profile_profilepicture"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default_profile_image.png",
                        null=True,
                        upload_to="accounts/profile_images",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Picture",
                "verbose_name_plural": "Profile Pictures",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="profilepicture",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profilepicture",
            ),
        ),
    ]
