# Generated by Django 5.0.6 on 2024-08-29 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_profilepicture_profile_profilepicture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilepicture",
            name="alt",
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profilepicture",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="profilepicture",
            name="format",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="profilepicture",
            name="height",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="profilepicture",
            name="size",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="profilepicture",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profilepicture",
            name="width",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profilepicture",
            name="image",
            field=models.ImageField(
                default="accounts/profile_images/default_profile_image.png",
                null=True,
                upload_to="accounts/profile_images",
            ),
        ),
    ]
