# Generated by Django 5.0.6 on 2024-08-29 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_profilepicture_alt_profilepicture_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profilepicture", name="alt",),
        migrations.AlterField(
            model_name="profile",
            name="profilepicture",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="accounts.profilepicture",
            ),
        ),
    ]
