# Generated by Django 5.0.6 on 2024-08-30 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_remove_profilepicture_alt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profilepicture",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profilepicture",
            ),
        ),
    ]
