# Generated by Django 5.1 on 2024-09-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_articleimage_alt_alter_article_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecomment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.article"
            ),
        ),
    ]
