# Generated by Django 5.0.6 on 2024-08-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_is_active"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="is_active",),
    ]
