# Generated by Django 5.0.6 on 2024-08-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_comment_articlecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecomment",
            name="email",
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="articlecomment",
            name="fullname",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
