# Generated by Django 5.0.6 on 2024-08-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_articlecomment_email_alter_articlecomment_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="slug", field=models.SlugField(max_length=500),
        ),
    ]
