# Generated by Django 5.0.6 on 2024-08-04 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.articlecategory",
            ),
        ),
    ]
