# Generated by Django 5.0.6 on 2024-08-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_rename_article_tag_article_article_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(null=True, upload_to="article_images"),
        ),
    ]
