# Generated by Django 5.0.6 on 2024-08-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_rename_message_articlecomment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.TextField(max_length=100000),
        ),
    ]
