# Generated by Django 5.0.6 on 2024-08-25 16:52

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_article_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=django_quill.fields.QuillField(max_length=100000),
        ),
    ]
