# Generated by Django 5.0.6 on 2024-08-30 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_articleimage"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="image",),
        migrations.AddField(
            model_name="article",
            name="article_image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.articleimage",
            ),
        ),
    ]
