# Generated by Django 5.0.6 on 2024-08-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_remove_article_image_article_article_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articleimage", old_name="update_at", new_name="updated_at",
        ),
    ]
