# Generated by Django 5.0.6 on 2024-08-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_rename_update_at_articleimage_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleimage",
            name="alt",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
