# Generated by Django 5.0.6 on 2024-08-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_articleimage_alt"),
    ]

    operations = [
        migrations.RemoveField(model_name="articleimage", name="alt",),
    ]
