# Generated by Django 5.0.6 on 2024-07-11 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=1000, unique=True)),
                ("brand_description", models.CharField(max_length=10000)),
                ("logo", models.ImageField(upload_to="shop/brands")),
                ("slug", models.SlugField(unique=True)),
            ],
            options={"verbose_name": "Brand", "verbose_name_plural": "Brands",},
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("img", models.ImageField(upload_to="shop/categories")),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.CreateModel(
            name="ProductSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subcategory_name", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("img", models.ImageField(upload_to="shop/subcategories")),
            ],
            options={
                "verbose_name": "Product Subcategory",
                "verbose_name_plural": "Product Subcategories",
            },
        ),
        migrations.CreateModel(
            name="ProductTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Product Tag",
                "verbose_name_plural": "Product Tags",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(unique=True)),
                ("product_name", models.CharField(max_length=1000, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("rate", models.IntegerField()),
                ("price", models.FloatField()),
                ("short_description", models.CharField(max_length=10000)),
                ("full_description", models.CharField(max_length=100000)),
                ("sku", models.IntegerField(default=286817, unique=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.brand"
                    ),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productcategory",
                    ),
                ),
                (
                    "product_subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productsubcategory",
                    ),
                ),
                ("product_tags", models.ManyToManyField(to="shop.producttags")),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Products",},
        ),
    ]
