# Generated by Django 5.1 on 2024-08-31 13:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="shop/brands")),
                ("size", models.IntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
                ("format", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Brand Logo",
                "verbose_name_plural": "Brand Logos",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True, unique=True)),
                ("hex", models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={"verbose_name": "Color", "verbose_name_plural": "Colors",},
        ),
        migrations.CreateModel(
            name="ProductCategoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="shop/categories")),
                ("size", models.IntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
                ("format", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Product Category Image",
                "verbose_name_plural": "Product Category Images",
            },
        ),
        migrations.CreateModel(
            name="ProductGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(null=True, upload_to="shop/products/gallery"),
                ),
            ],
            options={
                "verbose_name": "Product Gallery",
                "verbose_name_plural": "Products Gallery",
            },
        ),
        migrations.CreateModel(
            name="ProductSubCategoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="shop/subcategories")),
                ("size", models.IntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
                ("format", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Product SubCategory Image",
                "verbose_name_plural": "Product SubCategory Images",
            },
        ),
        migrations.CreateModel(
            name="ProductTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Product Tag",
                "verbose_name_plural": "Product Tags",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={"verbose_name": "Size", "verbose_name_plural": "Sizes",},
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, unique=True)),
                ("description", models.TextField(max_length=10000)),
                ("slug", models.SlugField(unique=True)),
                (
                    "logo",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.brandlogo",
                    ),
                ),
            ],
            options={"verbose_name": "Brand", "verbose_name_plural": "Brands",},
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category_image",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productcategoryimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.CreateModel(
            name="ProductSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="subcategories", to="shop.productcategory"
                    ),
                ),
                (
                    "subcategory_image",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productsubcategoryimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product SubCategory",
                "verbose_name_plural": "Product SubCategories",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.color"
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.size"
                    ),
                ),
            ],
            options={"verbose_name": "Stock", "verbose_name_plural": "Stocks",},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=1000, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.CharField(max_length=10000)),
                ("price", models.FloatField()),
                ("image", models.ImageField(upload_to="shop/products/thumbnails")),
                ("rate", models.IntegerField()),
                ("full_description", models.TextField(max_length=100000)),
                ("sku", models.IntegerField(default=0, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("sales_counter", models.IntegerField(default=0)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.brand"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productcategory",
                    ),
                ),
                ("gallery", models.ManyToManyField(to="shop.productgallery")),
                ("tags", models.ManyToManyField(to="shop.producttags")),
                ("quantity", models.ManyToManyField(to="shop.stock")),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Products",},
        ),
    ]
