# Generated by Django 5.0.6 on 2024-07-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.IntegerField(default=518622, unique=True),
        ),
    ]
