# Generated by Django 5.0.6 on 2024-08-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.IntegerField(null=True)),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=200)),
                ("house_number", models.CharField(max_length=200)),
                ("apartment_number", models.IntegerField()),
                ("postal_code", models.CharField(max_length=100)),
            ],
        ),
    ]
