# Generated by Django 5.0.6 on 2024-08-10 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_deliverydetails"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverydetails",
            options={
                "verbose_name": "Delivery Detail",
                "verbose_name_plural": "Delivery Details",
            },
        ),
    ]
