# Generated by Django 5.0.6 on 2024-08-10 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_deliverydetails_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverydetails",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
