# Generated by Django 5.1 on 2024-08-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_remove_product_gallery_product_gallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="rate", field=models.IntegerField(null=True),
        ),
    ]
