# Generated by Django 5.0.6 on 2024-07-11 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_remove_product_product_subcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.IntegerField(default=447577, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("951719fc-443c-468c-8730-bd44e2545315"), unique=True
            ),
        ),
    ]
