# Generated by Django 5.0.6 on 2024-08-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_deliverydetails_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverydetails",
            name="apartment_number",
            field=models.CharField(),
        ),
    ]
