# Generated by Django 5.0.6 on 2024-07-11 08:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_product_sku_alter_product_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("4e2fb78e-33d8-48c2-8c89-1f2581a494c8"), unique=True
            ),
        ),
    ]
