# Generated by Django 5.0.6 on 2024-08-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_productsubcategory_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliverydetails",
            old_name="apartment_number",
            new_name="apartmentnumber",
        ),
        migrations.RenameField(
            model_name="deliverydetails",
            old_name="house_number",
            new_name="housenumber",
        ),
        migrations.RenameField(
            model_name="deliverydetails", old_name="phone_number", new_name="phone",
        ),
        migrations.RenameField(
            model_name="deliverydetails", old_name="postal_code", new_name="postalcode",
        ),
    ]
