# Generated by Django 5.0.6 on 2024-07-11 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_color_size_product_created_at_product_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={"verbose_name": "Stock", "verbose_name_plural": "Stocks"},
        ),
        migrations.RemoveField(model_name="product", name="color",),
        migrations.RemoveField(model_name="product", name="size",),
        migrations.RemoveField(model_name="stock", name="product",),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="shop.stock"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("8654a95c-9165-4a06-94e2-7ee44024ecae"), unique=True
            ),
        ),
    ]
