# Generated by Django 5.1 on 2024-09-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_brandlogo_alt_productcategoryimage_alt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gallery",
            field=models.ManyToManyField(
                blank=True, related_name="product", to="shop.productimage"
            ),
        ),
    ]
