# Generated by Django 5.0.6 on 2024-08-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shop",
            "0007_rename_apartment_number_deliverydetails_apartmentnumber_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverydetails",
            name="phone",
            field=models.CharField(null=True),
        ),
    ]
