# Generated by Django 5.1 on 2024-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_product_gallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gallery",
            field=models.ManyToManyField(blank=True, to="shop.productimage"),
        ),
    ]
