# Generated by Django 5.0.6 on 2024-07-11 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_stock_options_remove_product_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="quantity",),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("d4916b10-45b4-4a2f-82b2-cd1c23a75e6f"), unique=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.ManyToManyField(to="shop.stock"),
        ),
    ]
