# Generated by Django 5.0.6 on 2024-07-11 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_remove_product_quantity_alter_product_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="color", name="hex", field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("867ab092-0128-401d-a5a8-29df9791d991"), unique=True
            ),
        ),
    ]
