# Generated by Django 5.1 on 2024-09-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_productsubcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsubcategory", name="slug", field=models.SlugField(),
        ),
    ]
