# Generated by Django 5.0.6 on 2024-07-11 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_color_hex_alter_product_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="shop/products/gallery"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="shop/products/thumbnails"),
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("6c7e92f1-b0f2-4da9-a57e-bd705fd9dbb3"), unique=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_gallery",
            field=models.ManyToManyField(to="shop.productgallery"),
        ),
    ]
