# Generated by Django 5.0.6 on 2024-08-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_deliverydetails_alter_onetimepassword_user_and_more"),
        ("shop", "0009_alter_deliverydetails_apartmentnumber_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="DeliveryDetails",),
    ]
