# Generated by Django 5.0.6 on 2024-07-11 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_productgallery_product_thumbnail_alter_product_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("26b75ccc-3134-4a24-83c0-29811df34b8a"), unique=True
            ),
        ),
    ]
