# Generated by Django 5.0.6 on 2024-08-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_delete_deliverydetails"),
    ]

    operations = [
        migrations.RemoveField(model_name="color", name="color",),
        migrations.AddField(
            model_name="color",
            name="name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="hex",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="size",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
