# Generated by Django 5.0.6 on 2024-07-11 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_product_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(upload_to="shop/products/thumbnails"),
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("9567c7d3-4f65-458e-8679-a9f7e27c669a"), unique=True
            ),
        ),
    ]
