# Generated by Django 5.0.6 on 2024-08-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_remove_color_color_color_name_alter_color_hex_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="productcategory", name="subcategory",),
        migrations.AddField(
            model_name="productsubcategory",
            name="categories",
            field=models.ManyToManyField(
                related_name="subcategories", to="shop.productcategory"
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
