# Generated by Django 5.1 on 2024-09-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_remove_productsubcategory_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsubcategory",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
