# Generated by Django 5.0.6 on 2024-08-28 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_remove_productcategory_subcategory_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="brand", old_name="logo", new_name="image",),
        migrations.RenameField(
            model_name="product", old_name="thumbnail", new_name="image",
        ),
    ]
