# Generated by Django 5.0.6 on 2024-07-11 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_product_thumbnail_alter_product_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("223c4c4b-e850-425f-bfd9-916121a3a33f"), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="image",
            field=models.ImageField(null=True, upload_to="shop/products/gallery"),
        ),
    ]
