# Generated by Django 5.1 on 2024-09-02 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_productsubcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsubcategory",
            name="categories",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="shop.productcategory",
            ),
        ),
    ]
