# Generated by Django 5.0.6 on 2024-08-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_rename_logo_brand_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(max_length=10000),
        ),
    ]
