# Generated by Django 5.0.6 on 2024-07-11 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_rename_brand_description_brand_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productcategory", old_name="img", new_name="image",
        ),
        migrations.RenameField(
            model_name="productcategory", old_name="category_name", new_name="name",
        ),
        migrations.RenameField(
            model_name="producttags", old_name="tag_name", new_name="name",
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("d08683c6-7e1f-4009-9cf0-0e88b7a88d9c"), unique=True
            ),
        ),
    ]
