# Generated by Django 5.0.6 on 2024-08-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_brand_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsubcategory",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="productsubcategory", name="slug", field=models.SlugField(),
        ),
    ]
