# Generated by Django 5.0.6 on 2024-08-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_alter_productsubcategory_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="productgallery", options={},),
        migrations.RenameField(model_name="size", old_name="size", new_name="name",),
    ]
