# Generated by Django 5.0.6 on 2024-07-11 11:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_rename_img_productcategory_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productsubcategory", old_name="img", new_name="image",
        ),
        migrations.RenameField(
            model_name="productsubcategory",
            old_name="subcategory_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("c3e8ef79-3d1d-45e8-af6f-37145be46f5f"), unique=True
            ),
        ),
    ]
