# Generated by Django 5.1 on 2024-09-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_product_subcategory"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="category",),
    ]
