# Generated by Django 5.0.6 on 2024-07-11 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_rename_img_productsubcategory_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock", old_name="amount", new_name="quantity",
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("7284b0d2-e583-4dcd-9fa5-77bd2ff84bf6"), unique=True
            ),
        ),
    ]
