# Generated by Django 5.0.6 on 2024-08-30 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_alter_productgallery_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="shop/brands")),
                ("size", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("format", models.CharField()),
            ],
        ),
        migrations.RemoveField(model_name="brand", name="image",),
        migrations.AddField(
            model_name="brand",
            name="logo",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.brandlogo",
            ),
        ),
    ]
