# Generated by Django 5.0.6 on 2024-07-11 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_rename_amount_stock_quantity_alter_product_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="product_category", new_name="category",
        ),
        migrations.RenameField(
            model_name="product", old_name="product_gallery", new_name="gallery",
        ),
        migrations.RenameField(
            model_name="product", old_name="product_name", new_name="name",
        ),
        migrations.RenameField(
            model_name="product", old_name="product_tags", new_name="tags",
        ),
        migrations.AlterIndexTogether(name="product", index_together=set(),),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("7f1a7a9d-929f-4968-9ed3-fd29cb0afeb4"), unique=True
            ),
        ),
    ]
