# Generated by Django 5.0.6 on 2024-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_brandlogo_remove_brand_image_brand_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brandlogo",
            options={
                "verbose_name": "Brand Logo",
                "verbose_name_plural": "Brand Logos",
            },
        ),
        migrations.AlterField(
            model_name="brandlogo", name="format", field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="brandlogo", name="height", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="brandlogo", name="size", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="brandlogo", name="width", field=models.IntegerField(null=True),
        ),
    ]
