# Generated by Django 5.1 on 2024-09-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsubcategory", name="subcategory_image",
        ),
        migrations.DeleteModel(name="ProductSubCategoryImage",),
    ]
