# Generated by Django 5.0.6 on 2024-08-30 15:40

import accounts.mixins
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_alter_brandlogo_options_alter_brandlogo_format_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="shop/categories")),
                ("size", models.IntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
                ("format", models.CharField(null=True)),
            ],
            options={
                "verbose_name": "Product Category Image",
                "verbose_name_plural": "Product Category Images",
            },
            bases=(accounts.mixins.SaveMixin, models.Model),
        ),
        migrations.RemoveField(model_name="productcategory", name="image",),
        migrations.AddField(
            model_name="productcategory",
            name="category_image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.productcategoryimage",
            ),
        ),
    ]
