# Generated by Django 5.0.6 on 2024-07-11 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_alter_product_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="full_description",
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("e0a63820-fcce-4172-b33c-144e4109729b"), unique=True
            ),
        ),
    ]
