# Generated by Django 5.1 on 2024-09-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_remove_productsubcategory_subcategory_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsubcategory",
            name="categories",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="shop.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
