# Generated by Django 5.0.6 on 2024-07-11 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_alter_product_full_description_alter_product_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("720c9ac6-ebd4-4d0b-826d-b3d1d1939937"), unique=True
            ),
        ),
    ]
