# Generated by Django 5.0.6 on 2024-08-30 19:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_productcategoryimage_remove_productcategory_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSubCategoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="shop/subcategories")),
                ("size", models.IntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
                ("format", models.CharField(null=True)),
            ],
            options={
                "verbose_name": "Product SubCategory Image",
                "verbose_name_plural": "Product SubCategory Images",
            },
        ),
        migrations.RemoveField(model_name="productsubcategory", name="image",),
        migrations.AddField(
            model_name="productsubcategory",
            name="subcategory_image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.productsubcategoryimage",
            ),
        ),
    ]
