# Generated by Django 5.1 on 2024-09-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_alter_productsubcategory_categories_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productsubcategory", old_name="categories", new_name="category",
        ),
    ]
