# Generated by Django 5.0.6 on 2024-07-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_alter_product_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "Product Gallery",
                "verbose_name_plural": "Products Gallery",
            },
        ),
    ]
