# Generated by Django 5.1 on 2024-09-04 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_productreview_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="quantity",),
        migrations.AddField(
            model_name="stock",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.product",
            ),
        ),
    ]
