# Generated by Django 5.1 on 2024-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0027_remove_productreview_rate_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="rate",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(name="Rate",),
    ]
