# Generated by Django 5.1 on 2024-09-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0037_productspecification_hip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productspecification",
            name="chest",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="hip",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="inches",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="knee",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="leg_opening",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="length",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="shoulder",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="size_guide_image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.sizeguideimage",
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="sleeve",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="waist",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="width",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
