# Generated by Django 5.1 on 2024-09-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0038_alter_productspecification_chest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_specification",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="shop.productspecification",
            ),
        ),
    ]
