# Generated by Django 5.1 on 2024-09-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0041_alter_product_product_specification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productspecification",
            name="washing_temperature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
